package com.metriql.jdbc

import java.io.InputStream
import java.io.Reader
import java.math.BigDecimal
import java.net.URL
import java.sql.Blob
import java.sql.Clob
import java.sql.Date
import java.sql.NClob
import java.sql.ParameterMetaData
import java.sql.PreparedStatement
import java.sql.Ref
import java.sql.ResultSet
import java.sql.ResultSetMetaData
import java.sql.RowId
import java.sql.SQLXML
import java.sql.Time
import java.sql.Timestamp
import java.util.Calendar

open class MetriqlPreparedStatement(
    val sql: String,
    rsType: Int? = null,
    rsConcurrency: Int? = null,
    rsHoldability: Int? = null,
    autoGeneratedKeys: Int? = null,
    columnIndexes: IntArray? = null,
    columnNames: Array<out String>? = null
) : MetriqlStatement(rsType, rsConcurrency, rsHoldability), PreparedStatement {
    override fun executeQuery(): ResultSet {
        TODO("not implemented")
    }

    override fun executeUpdate(): Int {
        TODO("not implemented")
    }

    override fun execute(): Boolean {
        TODO("not implemented")
    }

    override fun addBatch() {
        TODO("not implemented")
    }

    override fun setNull(parameterIndex: Int, sqlType: Int) {
        TODO("not implemented")
    }

    override fun setNull(parameterIndex: Int, sqlType: Int, typeName: String?) {
        TODO("not implemented")
    }

    override fun setBoolean(parameterIndex: Int, x: Boolean) {
        TODO("not implemented")
    }

    override fun setByte(parameterIndex: Int, x: Byte) {
        TODO("not implemented")
    }

    override fun setShort(parameterIndex: Int, x: Short) {
        TODO("not implemented")
    }

    override fun setInt(parameterIndex: Int, x: Int) {
        TODO("not implemented")
    }

    override fun setLong(parameterIndex: Int, x: Long) {
        TODO("not implemented")
    }

    override fun setFloat(parameterIndex: Int, x: Float) {
        TODO("not implemented")
    }

    override fun setDouble(parameterIndex: Int, x: Double) {
        TODO("not implemented")
    }

    override fun setBigDecimal(parameterIndex: Int, x: BigDecimal?) {
        TODO("not implemented")
    }

    override fun setString(parameterIndex: Int, x: String?) {
        TODO("not implemented")
    }

    override fun setBytes(parameterIndex: Int, x: ByteArray?) {
        TODO("not implemented")
    }

    override fun setDate(parameterIndex: Int, x: Date?) {
        TODO("not implemented")
    }

    override fun setDate(parameterIndex: Int, x: Date?, cal: Calendar?) {
        TODO("not implemented")
    }

    override fun setTime(parameterIndex: Int, x: Time?) {
        TODO("not implemented")
    }

    override fun setTime(parameterIndex: Int, x: Time?, cal: Calendar?) {
        TODO("not implemented")
    }

    override fun setTimestamp(parameterIndex: Int, x: Timestamp?) {
        TODO("not implemented")
    }

    override fun setTimestamp(parameterIndex: Int, x: Timestamp?, cal: Calendar?) {
        TODO("not implemented")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?, length: Int) {
        TODO("not implemented")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?, length: Long) {
        TODO("not implemented")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?) {
        TODO("not implemented")
    }

    override fun setUnicodeStream(parameterIndex: Int, x: InputStream?, length: Int) {
        TODO("not implemented")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?, length: Int) {
        TODO("not implemented")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?, length: Long) {
        TODO("not implemented")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?) {
        TODO("not implemented")
    }

    override fun clearParameters() {
        TODO("not implemented")
    }

    override fun setObject(parameterIndex: Int, x: Any?, targetSqlType: Int) {
        TODO("not implemented")
    }

    override fun setObject(parameterIndex: Int, x: Any?) {
        TODO("not implemented")
    }

    override fun setObject(parameterIndex: Int, x: Any?, targetSqlType: Int, scaleOrLength: Int) {
        TODO("not implemented")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?, length: Int) {
        TODO("not implemented")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?, length: Long) {
        TODO("not implemented")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?) {
        TODO("not implemented")
    }

    override fun setRef(parameterIndex: Int, x: Ref?) {
        TODO("not implemented")
    }

    override fun setBlob(parameterIndex: Int, x: Blob?) {
        TODO("not implemented")
    }

    override fun setBlob(parameterIndex: Int, inputStream: InputStream?, length: Long) {
        TODO("not implemented")
    }

    override fun setBlob(parameterIndex: Int, inputStream: InputStream?) {
        TODO("not implemented")
    }

    override fun setClob(parameterIndex: Int, x: Clob?) {
        TODO("not implemented")
    }

    override fun setClob(parameterIndex: Int, reader: Reader?, length: Long) {
        TODO("not implemented")
    }

    override fun setClob(parameterIndex: Int, reader: Reader?) {
        TODO("not implemented")
    }

    override fun setArray(parameterIndex: Int, x: java.sql.Array?) {
        TODO("not implemented")
    }

    override fun getMetaData(): ResultSetMetaData {
        TODO("not implemented")
    }

    override fun setURL(parameterIndex: Int, x: URL?) {
        TODO("not implemented")
    }

    override fun getParameterMetaData(): ParameterMetaData {
        TODO("not implemented")
    }

    override fun setRowId(parameterIndex: Int, x: RowId?) {
        TODO("not implemented")
    }

    override fun setNString(parameterIndex: Int, value: String?) {
        TODO("not implemented")
    }

    override fun setNCharacterStream(parameterIndex: Int, value: Reader?, length: Long) {
        TODO("not implemented")
    }

    override fun setNCharacterStream(parameterIndex: Int, value: Reader?) {
        TODO("not implemented")
    }

    override fun setNClob(parameterIndex: Int, value: NClob?) {
        TODO("not implemented")
    }

    override fun setNClob(parameterIndex: Int, reader: Reader?, length: Long) {
        TODO("not implemented")
    }

    override fun setNClob(parameterIndex: Int, reader: Reader?) {
        TODO("not implemented")
    }

    override fun setSQLXML(parameterIndex: Int, xmlObject: SQLXML?) {
        TODO("not implemented")
    }
}
