package com.metriql.jdbc

import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLWarning
import java.sql.Statement

open class MetriqlStatement(rsType: Int? = null, rsConcurrency: Int? = null, rsHoldability: Int? = null) : Statement {
    override fun <T : Any?> unwrap(iface: Class<T>?) = null!!

    override fun isWrapperFor(iface: Class<*>?): Boolean {
        TODO("not implemented")
    }

    override fun close() {
        TODO("not implemented")
    }

    override fun executeQuery(sql: String?): ResultSet {
        TODO("not implemented")
    }

    override fun executeUpdate(sql: String?): Int {
        TODO("not implemented")
    }

    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int {
        TODO("not implemented")
    }

    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int {
        TODO("not implemented")
    }

    override fun executeUpdate(sql: String?, columnNames: Array<out String>?): Int {
        TODO("not implemented")
    }

    override fun getMaxFieldSize(): Int {
        TODO("not implemented")
    }

    override fun setMaxFieldSize(max: Int) {
        TODO("not implemented")
    }

    override fun getMaxRows(): Int {
        TODO("not implemented")
    }

    override fun setMaxRows(max: Int) {
        TODO("not implemented")
    }

    override fun setEscapeProcessing(enable: Boolean) {
        TODO("not implemented")
    }

    override fun getQueryTimeout(): Int {
        TODO("not implemented")
    }

    override fun setQueryTimeout(seconds: Int) {
        TODO("not implemented")
    }

    override fun cancel() {
        TODO("not implemented")
    }

    override fun getWarnings(): SQLWarning {
        TODO("not implemented")
    }

    override fun clearWarnings() {
        TODO("not implemented")
    }

    override fun setCursorName(name: String?) {
        TODO("not implemented")
    }

    override fun execute(sql: String?): Boolean {
        TODO("not implemented")
    }

    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean {

        TODO("not implemented")
    }

    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean {
        TODO("not implemented")
    }

    override fun execute(sql: String?, columnNames: Array<out String>?): Boolean {
        TODO("not implemented")
    }

    override fun getResultSet(): ResultSet {
        TODO("not implemented")
    }

    override fun getUpdateCount(): Int {
        TODO("not implemented")
    }

    override fun getMoreResults(): Boolean {
        TODO("not implemented")
    }

    override fun getMoreResults(current: Int): Boolean {
        TODO("not implemented")
    }

    override fun setFetchDirection(direction: Int) {
        TODO("not implemented")
    }

    override fun getFetchDirection(): Int {
        TODO("not implemented")
    }

    override fun setFetchSize(rows: Int) {
        TODO("not implemented")
    }

    override fun getFetchSize(): Int {
        TODO("not implemented")
    }

    override fun getResultSetConcurrency(): Int {
        TODO("not implemented")
    }

    override fun getResultSetType(): Int {
        TODO("not implemented")
    }

    override fun addBatch(sql: String?) {
        TODO("not implemented")
    }

    override fun clearBatch() {
        TODO("not implemented")
    }

    override fun executeBatch(): IntArray {
        TODO("not implemented")
    }

    override fun getConnection(): Connection {
        TODO("not implemented")
    }

    override fun getGeneratedKeys(): ResultSet {
        TODO("not implemented")
    }

    override fun getResultSetHoldability(): Int {
        TODO("not implemented")
    }

    override fun isClosed(): Boolean {
        TODO("not implemented")
    }

    override fun setPoolable(poolable: Boolean) {
        TODO("not implemented")
    }

    override fun isPoolable(): Boolean {
        TODO("not implemented")
    }

    override fun closeOnCompletion() {
        TODO("not implemented")
    }

    override fun isCloseOnCompletion(): Boolean {
        TODO("not implemented")
    }
}
